In [4]:
import pandas as pd

In [6]:
df25 = pd.read_csv("full_data_2025.csv")
df25

,transit_timestamp,station_complex,borough,fare_class_category,ridership,transfers
0,4/30/25 23:00,23 St-Baruch College (6),Manhattan,OMNY - Seniors & Disability,5,0
1,4/30/25 23:00,23 St-Baruch College (6),Manhattan,Metrocard - Full Fare,23,1
2,4/30/25 23:00,23 St-Baruch College (6),Manhattan,OMNY - Students,15,1
3,4/30/25 23:00,23 St-Baruch College (6),Manhattan,Metrocard - Fair Fare,16,0
4,4/30/25 23:00,23 St-Baruch College (6),Manhattan,Metrocard - Other,6,0
...,...,...,...,...,...,...
19886,2/1/25 0:00,23 St-Baruch College (6),Manhattan,Metrocard - Full Fare,20,2
19887,2/1/25 0:00,23 St-Baruch College (6),Manhattan,Metrocard - Other,2,0
19888,2/1/25 0:00,23 St-Baruch College (6),Manhattan,Metrocard - Unlimited 7-Day,10,0
19889,2/1/25 0:00,23 St-Baruch College (6),Manhattan,Metrocard - Fair Fare,6,0
19890,2/1/25 0:00,23 St-Baruch College (6),Manhattan,Metrocard - Seniors & Disability,2,0

In [20]:
df25.info()

<class 'pandas.DataFrame'>
RangeIndex: 19891 entries, 0 to 19890
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   transit_timestamp    19891 non-null  str
 1   station_complex      19891 non-null  str
 2   borough              19891 non-null  str
 3   fare_class_category  19891 non-null  str
 4   ridership            19891 non-null  str
 5   transfers            19891 non-null  int64
dtypes: int64(1), str(5)
memory usage: 932.5 KB

In [65]:
# Remove commas and convert to numbers- GOOGLE GEMINI response when asked how to remove commas
df25["ridership"] = df25["ridership"].astype(str).str.replace(",", "")
df25["ridership"] = pd.to_numeric(df25["ridership"])
df25

,transit_timestamp,station_complex,borough,fare_class_category,ridership,transfers
0,4/30/25 23:00,23 St-Baruch College (6),Manhattan,OMNY - Seniors & Disability,5,0
1,4/30/25 23:00,23 St-Baruch College (6),Manhattan,Metrocard - Full Fare,23,1
2,4/30/25 23:00,23 St-Baruch College (6),Manhattan,OMNY - Students,15,1
3,4/30/25 23:00,23 St-Baruch College (6),Manhattan,Metrocard - Fair Fare,16,0
4,4/30/25 23:00,23 St-Baruch College (6),Manhattan,Metrocard - Other,6,0
...,...,...,...,...,...,...
19886,2/1/25 0:00,23 St-Baruch College (6),Manhattan,Metrocard - Full Fare,20,2
19887,2/1/25 0:00,23 St-Baruch College (6),Manhattan,Metrocard - Other,2,0
19888,2/1/25 0:00,23 St-Baruch College (6),Manhattan,Metrocard - Unlimited 7-Day,10,0
19889,2/1/25 0:00,23 St-Baruch College (6),Manhattan,Metrocard - Fair Fare,6,0
19890,2/1/25 0:00,23 St-Baruch College (6),Manhattan,Metrocard - Seniors & Disability,2,0

In [66]:
df25["ridership"] = pd.to_numeric(df25["ridership"])
df25# Assuming 'df' is your DataFrame
total_ridership1 = df["ridership"].sum()

,transit_timestamp,station_complex,borough,fare_class_category,ridership,transfers
0,4/30/25 23:00,23 St-Baruch College (6),Manhattan,OMNY - Seniors & Disability,5,0
1,4/30/25 23:00,23 St-Baruch College (6),Manhattan,Metrocard - Full Fare,23,1
2,4/30/25 23:00,23 St-Baruch College (6),Manhattan,OMNY - Students,15,1
3,4/30/25 23:00,23 St-Baruch College (6),Manhattan,Metrocard - Fair Fare,16,0
4,4/30/25 23:00,23 St-Baruch College (6),Manhattan,Metrocard - Other,6,0
...,...,...,...,...,...,...
19886,2/1/25 0:00,23 St-Baruch College (6),Manhattan,Metrocard - Full Fare,20,2
19887,2/1/25 0:00,23 St-Baruch College (6),Manhattan,Metrocard - Other,2,0
19888,2/1/25 0:00,23 St-Baruch College (6),Manhattan,Metrocard - Unlimited 7-Day,10,0
19889,2/1/25 0:00,23 St-Baruch College (6),Manhattan,Metrocard - Fair Fare,6,0
19890,2/1/25 0:00,23 St-Baruch College (6),Manhattan,Metrocard - Seniors & Disability,2,0

In [67]:

df = df25["ridership"].sum()
df

np.int64(1584281)

In [21]:
df26 = pd.read_csv("full_data_2026.csv")
df26

,transit_timestamp,station_complex,fare_class_category,ridership,transfers
0,4/30/26 23:00,23 St-Baruch College (6),OMNY - Full Fare,309,8
1,4/30/26 23:00,23 St-Baruch College (6),OMNY - Students,16,0
2,4/30/26 23:00,23 St-Baruch College (6),OMNY - Seniors & Disability,16,2
3,4/30/26 23:00,23 St-Baruch College (6),OMNY - Other,2,0
4,4/30/26 23:00,23 St-Baruch College (6),Metrocard - Other,2,0
...,...,...,...,...,...
13174,2/1/26 0:00,23 St-Baruch College (6),Metrocard - Unlimited 30-Day,3,0
13175,2/1/26 0:00,23 St-Baruch College (6),OMNY - Seniors & Disability,3,0
13176,2/1/26 0:00,23 St-Baruch College (6),OMNY - Other,2,0
13177,2/1/26 0:00,23 St-Baruch College (6),OMNY - Students,5,0
13178,2/1/26 0:00,23 St-Baruch College (6),OMNY - Fair Fare,3,0

In [34]:
riders25 = df25["ridership"]
riders_int25 = riders.apply(lambda x: x.replace(',', '')).astype(int)
riders_int25

0        309
1         16
2         16
3          2
4          2
        ...
13174      3
13175      3
13176      2
13177      5
13178      3
Name: ridership, Length: 13179, dtype: int64

In [35]:
df25.info()

<class 'pandas.DataFrame'>
RangeIndex: 19891 entries, 0 to 19890
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   transit_timestamp    19891 non-null  str
 1   station_complex      19891 non-null  str
 2   borough              19891 non-null  str
 3   fare_class_category  19891 non-null  str
 4   ridership            19891 non-null  str
 5   transfers            19891 non-null  int64
dtypes: int64(1), str(5)
memory usage: 932.5 KB

In [36]:
riders26 = df26["ridership"]
riders_int26 = riders.apply(lambda x: x.replace(',', '')).astype(int)
riders_int26

0        309
1         16
2         16
3          2
4          2
        ...
13174      3
13175      3
13176      2
13177      5
13178      3
Name: ridership, Length: 13179, dtype: int64

In [68]:
# Remove commas and convert to numbers- GOOGLE GEMINI response when asked how to remove commas
df26["ridership"] = df26["ridership"].astype(str).str.replace(",", "")
df26["ridership"] = pd.to_numeric(df26["ridership"])
df26

,transit_timestamp,station_complex,fare_class_category,ridership,transfers
0,4/30/26 23:00,23 St-Baruch College (6),OMNY - Full Fare,309,8
1,4/30/26 23:00,23 St-Baruch College (6),OMNY - Students,16,0
2,4/30/26 23:00,23 St-Baruch College (6),OMNY - Seniors & Disability,16,2
3,4/30/26 23:00,23 St-Baruch College (6),OMNY - Other,2,0
4,4/30/26 23:00,23 St-Baruch College (6),Metrocard - Other,2,0
...,...,...,...,...,...
13174,2/1/26 0:00,23 St-Baruch College (6),Metrocard - Unlimited 30-Day,3,0
13175,2/1/26 0:00,23 St-Baruch College (6),OMNY - Seniors & Disability,3,0
13176,2/1/26 0:00,23 St-Baruch College (6),OMNY - Other,2,0
13177,2/1/26 0:00,23 St-Baruch College (6),OMNY - Students,5,0
13178,2/1/26 0:00,23 St-Baruch College (6),OMNY - Fair Fare,3,0

In [73]:
df26["ridership"] = pd.to_numeric(df26["ridership"])
df26
total_ridership2 = df26["ridership"].sum()

In [74]:
df2 = df26["ridership"].sum()
df2

np.int64(1661233)

In [75]:
df26.info()

<class 'pandas.DataFrame'>
RangeIndex: 13179 entries, 0 to 13178
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   transit_timestamp    13179 non-null  str
 1   station_complex      13179 non-null  str
 2   fare_class_category  13179 non-null  str
 3   ridership            13179 non-null  int64
 4   transfers            13179 non-null  int64
dtypes: int64(2), str(3)
memory usage: 514.9 KB

In [76]:
df25.info()

<class 'pandas.DataFrame'>
RangeIndex: 19891 entries, 0 to 19890
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   transit_timestamp    19891 non-null  str
 1   station_complex      19891 non-null  str
 2   borough              19891 non-null  str
 3   fare_class_category  19891 non-null  str
 4   ridership            19891 non-null  int64
 5   transfers            19891 non-null  int64
dtypes: int64(2), str(4)
memory usage: 932.5 KB

In [82]:

total_ridership25 = df25["ridership"].sum()
print(total_ridership25)

1584281

In [83]:

total_ridership26 = df26["ridership"].sum()
print(total_ridership26)

1661233

In [84]:
# 1. Convert the date column to datetime format-- asked gemini
df25["transit_timestamp"] = pd.to_datetime(df25["transit_timestamp"])

# 2. Group by month and sum the ridership
monthly_df25 = df25.groupby(df25["transit_timestamp"].dt.to_period("M"))["ridership"].sum().reset_index()

# 3. View the result
print(monthly_df25)

/var/folders/zb/w079twms5bl1g4m1165bkh8c0000gn/T/ipykernel_95272/1700953497.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df25["transit_timestamp"] = pd.to_datetime(df25["transit_timestamp"])

  transit_timestamp  ridership
0           2025-02     495408
1           2025-03     554263
2           2025-04     534610

In [85]:
for df in [df25, df26]:
    df["transit_timestamp"] = pd.to_datetime(df["transit_timestamp"])
    monthly_summary = df.groupby(df["transit_timestamp"].dt.to_period("M"))["ridership"].sum().reset_index()
    print(monthly_summary)

  transit_timestamp  ridership
0           2025-02     495408
1           2025-03     554263
2           2025-04     534610

/var/folders/zb/w079twms5bl1g4m1165bkh8c0000gn/T/ipykernel_95272/1333916835.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["transit_timestamp"] = pd.to_datetime(df["transit_timestamp"])

  transit_timestamp  ridership
0           2026-02     506661
1           2026-03     602980
2           2026-04     551592